version: 0.2

env:
  variables:
    DJANGO_SETTINGS_MODULE: "config.settings.prod"
  secrets-manager:
    DJANGO_SECRET_KEY: "prod/portfolio/secret:DJANGO_SECRET_KEY"
  parameter-store:
    ALLOWED_HOSTS: "/prod/portfolio/parameter/allowed_hosts"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Preparing SAM build..."
      - python manage.py collectstatic --noinput
  build:
    commands:
      - echo "Running sam build..."
      - sam build --use-container
  post_build:
    commands:
      - echo "Running sam package..."
      - sam package --output-template-file packaged.yaml --s3-bucket $S3Bucket

artifacts:
  type: zip
  files:
    - packaged.yaml
