version: 0.2

env:
  variables:
    DJANGO_SETTINGS_MODULE: "config.settings.prod"
    ENV: "prod"
    
  # Secrets Managerから取得するすべての秘密情報を定義
  secrets-manager:
    DJANGO_SECRET_KEY: "prod/portfolio/secret:DJANGO_SECRET_KEY"
    EMAIL_HOST_USER: "prod/portfolio/secret:EMAIL_HOST_USER"
    EMAIL_HOST_PASSWORD: "prod/portfolio/secret:EMAIL_HOST_PASSWORD"
    GOOGLE_CLIENT_ID: "prod/portfolio/secret:GOOGLE_CLIENT_ID"
    GOOGLE_CLIENT_SECRET: "prod/portfolio/secret:GOOGLE_CLIENT_SECRET"
    GITHUB_CLIENT_ID: "prod/portfolio/secret:GITHUB_CLIENT_ID"
    GITHUB_CLIENT_SECRET: "prod/portfolio/secret:GITHUB_CLIENT_SECRET"

  # Parameter Storeから取得するすべてのパラメータを定義
  parameter-store:
    ALLOWED_HOSTS: "/prod/portfolio/parameter/allowed_hosts"
    CSRF_TRUSTED_ORIGINS: "/prod/portfolio/parameter/csrf_trusted_origins"
    DEFAULT_FROM_EMAIL: "/prod/portfolio/parameter/default_from_email"
    DEFAULT_TO_EMAIL: "/prod/portfolio/parameter/default_to_mail"
    EMAIL_HOST: "/prod/portfolio/parameter/email_host"
    EMAIL_PORT: "/prod/portfolio/parameter/email_port"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Preparing SAM build..."
      # 翻訳ファイル処理を条件付きで実行
      - echo "Setting up locale directory..."
      - mkdir -p locale
      
      # 既存の翻訳ファイルがあるかチェックしてから実行
      - echo "Generating and compiling translation files..."
      - |
        if [ -f "templates/portfolio_base.html" ]; then
          echo "Found templates, generating translation files..."
          python manage.py makemessages -l ja --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for ja failed, continuing..."
          python manage.py makemessages -l en --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for en failed, continuing..."
          python manage.py makemessages -l fr --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for fr failed, continuing..."
          python manage.py makemessages -l es --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for es failed, continuing..."
          python manage.py makemessages -l ru --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for ru failed, continuing..."
          python manage.py makemessages -l zh-hans --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for zh-hans failed, continuing..."
          python manage.py makemessages -l ar --ignore=venv --ignore=.venv --ignore=node_modules || echo "makemessages for ar failed, continuing..."
          python manage.py compilemessages || echo "compilemessages failed, continuing..."
        else
          echo "No templates found, skipping translation file generation"
        fi
        
      # 静的ファイルの収集
      - python manage.py collectstatic --noinput
      - echo "Syncing static files to S3..."
      - BUCKET_NAME="cobaemon-serverless-portfolio-${ENV}-static"
      - aws s3 sync staticfiles/ s3://${BUCKET_NAME}/ --delete
  build:
    commands:
      - echo "Running sam build..."
      - sam build --use-container
  post_build:
    commands:
      - echo "Running sam package..."
      - sam package --output-template-file packaged.yaml --s3-bucket $S3Bucket

artifacts:
  files:
    - packaged.yaml
