version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Preparing SAM build..."
  build:
    commands:
      - sam build --use-container
  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket cobaemon-serverless-portfolio
artifacts:
  type: zip
  files:
    - packaged.yaml
