AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Serverless Portfolioアプリケーションの依存リソース（S3バケット、CloudFront Origin Access Control等）"

Parameters:
  Env:
    Type: String
    Default: prod
    AllowedValues: [dev, prod]
    Description: "デプロイ環境（dev または prod）"
  
  # 既存のCloudFront Origin Access Control ID（新規作成しない場合に指定）
  ExistingOACId:
    Type: String
    Default: ""
    Description: "既存のCloudFront Origin Access Control ID（新規作成しない場合に指定）"

Conditions:
  # 既存OAC IDが指定されていない場合のみ新規作成
  CreateOAC: !Equals [!Ref ExistingOACId, ""]

Resources:
  # 静的ファイル配信用S3バケット
  # CSS、JavaScript、画像などの静的ファイルを格納
  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cobaemon-serverless-portfolio-${Env}-static"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3000

  # CloudFrontからS3へのアクセスを制御するOrigin Access Control
  # S3バケットへの直接アクセスを防ぎ、CloudFront経由でのみアクセス可能にする
  # 既存OAC IDが指定されている場合は新規作成しない
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Condition: CreateOAC
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "OAC-for-cobaemon-serverless-portfolio-${Env}-static"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # S3バケットポリシー
  # CloudFrontからのアクセスのみを許可し、セキュリティを確保
  StaticFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticFilesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFront
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${StaticFilesBucket}/*"
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"
          - Sid: AllowAccountRead
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${StaticFilesBucket}"
              - !Sub "arn:aws:s3:::${StaticFilesBucket}/*"

Outputs:
  # Origin Access Control IDをエクスポート
  # 新規作成した場合はそのID、既存の場合は指定されたIDを使用
  OACId:
    Description: "CloudFront用のOrigin Access Control ID"
    Value: !If [CreateOAC, !GetAtt CloudFrontOriginAccessControl.Id, !Ref ExistingOACId]
    Export:
      Name: !Sub "cobaemon-portfolio-${Env}-oac-id"
