version = 0.1
[default.deploy.parameters]
stack_name = "cobaemon-serverless-portfolio-stack"
resolve_s3 = true
s3_prefix = "cobaemon-serverless-portfolio-stack"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Env=\"prod\" S3Bucket=\"cobaemon-serverless-portfolio-prod-artifacts\" CodePipelineName=\"cobaemon-serverless-portfolio-pipeline\" FullRepositoryId=\"cobaemon/ServerlessPortfolio\" BranchName=\"main\" StackName=\"cobaemon-serverless-portfolio-stack\" TemplatePath=\"packaged.yaml\" AllowedOrigin=\"/prod/portfolio/parameter/csrf_trusted_origins\" AllowedHosts=\"/prod/portfolio/parameter/allowed_hosts\" DomainName=\"serverless.portfolio.cobaemon.com\""
image_repositories = []
profile = "aws_portfolio_profile"
confirm_changeset = true
