version = 0.1
[default.deploy.parameters]
stack_name = "CobaemonServerlessPortfolio-Pipeline"
resolve_s3 = true
s3_prefix = "CobaemonServerlessPortfolio-Pipeline"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Env=\"prod\""
image_repositories = []
profile = "aws_portfolio_profile"
confirm_changeset = true
