# Generated by Django 5.0.6 on 2024-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
