# Generated by Django 5.0.6 on 2024-06-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_logincode_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login_code',
        ),
        migrations.DeleteModel(
            name='LoginCode',
        ),
    ]
