# Generated by Django 5.0.6 on 2024-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usertotpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='use_one_time_password',
            field=models.BooleanField(default=False),
        ),
    ]
