# Generated by Django 5.0.6 on 2024-06-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_use_one_time_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTOTPDevice',
        ),
    ]
